### ISSUE TITLE
Expired TLS certificate on https://schemablocks.org/

### ISSUE THREAD

**Issue by jfuerth** [ga4gh-schemablocks/ga4gh-schemablocks.github.io#18]
The schemablocks.org site is currently unreachable because its TLS certificate expired today.

**Comment by mbaudis** [comment]
@jfuerth Thanks for the note! Also WTF since it is a typical Cloudflare <-> Github setup? I'll explore...

**Comment by mbaudis** [comment]
@jfuerth ... and a correction; there were still nameserver services by the domain name provider; so not a Cloudflare problem (but then still a Github one since it provides the CERTS). Changed to Cloudflare, for consistency; patience ...

**Comment by mbaudis** [comment]
@jfuerth Should be good now. I guess this started w/ some Github hiccup; now seems to work (also set to "full encryption" on Cloudflare) although there again is a disconcerting certificate note "Certificate provisioning will retry automatically..." on GH.

**Comment by jfuerth** [comment]
Thanks for the fix. Everything looks good on our side now!
