### ISSUE TITLE
Create documentation for ID/CURIE use & formats

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-schemablocks/ga4gh-schemablocks.github.io#2]
One important documentation needed is a recommendation for the correct use of identifiers for ontology classes in GA4GH objects & APIs. There had been [comments on errors/aberrant use](https://github.com/ga4gh-metadata/SchemaBlocks/issues/10) in the  ga4gh-metadata SchemaBlocks prototype.
The current site contains a [placeholder page](https://github.com/ga4gh-schemablocks/ga4gh-schemablocks.github.io/blob/master/pages/_formats/identifiers-curies.md) for a first documentation. Please (@cmungall, @mcourtot, other GA4GH::GKS...) - it would be nice to fill this in with details!

**Comment by cmungall** [comment]
can you ping me about this again in a couple of weeks?

**Comment by mbaudis** [comment]
@cmungall @mellybelly Will do ...
